"""
Localization utility for providing multilingual text.
"""

LOCALIZATION = {
    "en": {
        "website_language": "🌐 Website Language",
        "admin_access": "👑 Admin Access",
        "admin_key_placeholder": "Enter Admin Key",
        "admin_success": "Admin Mode Activated!",
        "admin_fail": "Invalid Admin Key",
        "admin_status": "Status: Unlimited Access",
        "settings_header": "⚙️ Settings",
        "tone_label": "Tone",
        "pricing_header": "💰 Pricing",
        "pricing_info": "Free Trial: {limit} CV generation\n\nPaid: SAR {price} per CV",
        "version_info": "Version {version}",
        "main_title": "📄 CVTailor",
        "subtitle": "Generate Your Professional CV in 60 Seconds",
        "form_header": "📝 CV Generation Form",
        "required_fields": "🔴 Required Fields",
        "job_description_label": "Job Description *",
        "job_description_placeholder": "Paste the job description here...",
        "education_label": "Education *",
        "education_placeholder": "Describe your education background, degrees, institutions, years...",
        "personal_info": "👤 Personal Information",
        "full_name_label": "Full Name",
        "full_name_placeholder": "Your full name",
        "email_label": "Email",
        "email_placeholder": "your.email@example.com",
        "phone_label": "Phone",
        "phone_placeholder": "+966 50 123 4567",
        "location_label": "Location",
        "location_placeholder": "City, Country",
        "linkedin_label": "LinkedIn",
        "linkedin_placeholder": "linkedin.com/in/yourprofile",
        "website_label": "Website/Portfolio",
        "website_placeholder": "yourwebsite.com",
        "experience_label": "💼 Work Experience",
        "experience_placeholder": "Describe your work experience, roles, companies, achievements...",
        "experience_help": "You can describe your experience naturally. Include company names, roles, dates, and key achievements.",
        "skills_header": "🛠️ Skills",
        "technical_skills_label": "Technical Skills",
        "technical_skills_placeholder": "Programming languages, tools, technologies...",
        "soft_skills_label": "Soft Skills",
        "soft_skills_placeholder": "Leadership, communication, problem-solving...",
        "projects_label": "🚀 Projects",
        "projects_placeholder": "Describe your key projects, their impact, technologies used...",
        "projects_help": "Include project names, your role, technologies, and quantifiable results.",
        "additional_info": "📚 Additional Information",
        "certifications_label": "Certifications",
        "certifications_placeholder": "Professional certifications, courses, training...",
        "languages_label": "Languages",
        "languages_placeholder": "English (Native), Arabic (Fluent)",
        "achievements_label": "Achievements & Awards",
        "achievements_placeholder": "Awards, recognitions, publications, patents...",
        "interests_label": "Interests",
        "interests_placeholder": "Professional interests, hobbies, causes...",
        "delivery_options": "📧 Delivery Options (Optional)",
        "delivery_email_label": "Send documents to this email:",
        "delivery_email_confirm": "Confirm email:",
        "generate_button": "🚀 Generate CV",
        "spinner_generating_cv": "Generating your CV...",
        "spinner_generating_cl": "Generating cover letter...",
        "spinner_creating_pdf": "Creating PDF document...",
        "spinner_sending_email": "Sending email...",
        "email_success": "Your documents have been sent to {email}!",
        "email_fail": "Failed to send email: {error}",
        "generation_success": "✅ CV Generated Successfully!",
        "preview_tab": "📄 CV Preview",
        "cover_letter_tab": "📝 Cover Letter",
        "suggestions_tab": "💡 Suggestions",
        "interview_prep_tab": "❓ Interview Prep",
        "download_tab": "📥 Download",
        "cover_letter_header": "🖋️ Your Personalized Cover Letter",
        "download_header": "📥 Download Your Professional CV",
        "download_info_admin": "Admin access: You have unlimited downloads.",
        "download_info_user": "Your formatted, two-column CV is ready for download as a PDF below.",
        "download_purchase_warning": "Free trial used. Purchase required for another download.",
        "download_warning": "Free trial used. Purchase required for another download.",
        "purchase_button": "💳 Purchase for SAR {price}",
        "payment_info": "Payment integration coming soon...",
        "download_button_label": "📄 Download PDF",
        "download_caption": "This will use your free trial credit.",
        "pdf_fail": "Sorry, we couldn't generate the PDF. Please try again.",
        "docx_button_label": "📝 Download DOCX (Coming Soon)",
        "feedback_header": "Was this helpful?",
        "feedback_yes": "👍 Yes",
        "feedback_no": "👎 No",
        "feedback_rate": "⭐ Rate",
        "feedback_thanks": "Thank you for your feedback!",
        "feedback_improve": "We'll work to improve. Thank you!",
        "rating_slider": "Rate your experience",
        "submit_rating": "Submit Rating",
        "rating_thanks": "Thank you for your {rating}-star rating!",
    },
    "ar": {
        "website_language": "🌐 لغة الموقع",
        "admin_access": "👑 وصول المسؤول",
        "admin_key_placeholder": "أدخل مفتاح المسؤول",
        "admin_success": "تم تفعيل وضع المسؤول!",
        "admin_fail": "مفتاح المسؤول غير صالح",
        "admin_status": "الحالة: وصول غير محدود",
        "settings_header": "⚙️ الإعدادات",
        "tone_label": "نبرة الصوت",
        "pricing_header": "💰 الأسعار",
        "pricing_info": "تجربة مجانية: {limit} سيرة ذاتية\n\nمدفوع: {price} ريال سعودي لكل سيرة ذاتية",
        "version_info": "الإصدار {version}",
        "main_title": "📄 مُخصص السيرة الذاتية",
        "subtitle": "أنشئ سيرتك الذاتية الاحترافية في 60 ثانية",
        "form_header": "📝 نموذج إنشاء السيرة الذاتية",
        "required_fields": "🔴 الحقول المطلوبة",
        "job_description_label": "الوصف الوظيفي *",
        "job_description_placeholder": "الصق الوصف الوظيفي هنا...",
        "education_label": "التعليم *",
        "education_placeholder": "صف خلفيتك التعليمية، الشهادات، الجامعات، السنوات...",
        "personal_info": "👤 المعلومات الشخصية",
        "full_name_label": "الاسم الكامل",
        "full_name_placeholder": "اسمك الكامل",
        "email_label": "البريد الإلكتروني",
        "email_placeholder": "your.email@example.com",
        "phone_label": "رقم الهاتف",
        "phone_placeholder": "+966 50 123 4567",
        "location_label": "الموقع",
        "location_placeholder": "المدينة، الدولة",
        "linkedin_label": "حساب لينكدإن",
        "linkedin_placeholder": "linkedin.com/in/yourprofile",
        "website_label": "الموقع الإلكتروني/ملف الأعمال",
        "website_placeholder": "yourwebsite.com",
        "experience_label": "💼 الخبرة العملية",
        "experience_placeholder": "صف خبراتك العملية، المناصب، الشركات، الإنجازات...",
        "experience_help": "يمكنك وصف خبرتك بشكل طبيعي. اذكر أسماء الشركات، المناصب، التواريخ، والإنجازات الرئيسية.",
        "skills_header": "🛠️ المهارات",
        "technical_skills_label": "المهارات التقنية",
        "technical_skills_placeholder": "لغات البرمجة، الأدوات، التقنيات...",
        "soft_skills_label": "المهارات الشخصية",
        "soft_skills_placeholder": "القيادة، التواصل، حل المشكلات...",
        "projects_label": "🚀 المشاريع",
        "projects_placeholder": "صف مشاريعك الرئيسية، تأثيرها، والتقنيات المستخدمة...",
        "projects_help": "اذكر أسماء المشاريع، دورك، التقنيات، والنتائج القابلة للقياس.",
        "additional_info": "📚 معلومات إضافية",
        "certifications_label": "الشهادات",
        "certifications_placeholder": "الشهادات المهنية، الدورات، التدريب...",
        "languages_label": "اللغات",
        "languages_placeholder": "الإنجليزية (لغة أم)، العربية (بطلاقة)",
        "achievements_label": "الإنجازات والجوائز",
        "achievements_placeholder": "الجوائز، التكريمات، المنشورات، براءات الاختراع...",
        "interests_label": "الاهتمامات",
        "interests_placeholder": "الاهتمامات المهنية، الهوايات، القضايا...",
        "delivery_options": "📧 خيارات التسليم (اختياري)",
        "delivery_email_label": "أرسل المستندات إلى هذا البريد الإلكتروني:",
        "delivery_email_confirm": "تأكيد البريد الإلكتروني:",
        "generate_button": "🚀 أنشئ السيرة الذاتية",
        "spinner_generating_cv": "جاري إنشاء سيرتك الذاتية...",
        "spinner_generating_cl": "جاري إنشاء خطاب التغطية...",
        "spinner_creating_pdf": "جاري إنشاء مستند PDF...",
        "spinner_sending_email": "جاري إرسال البريد الإلكتروني...",
        "email_success": "تم إرسال مستنداتك إلى {email}!",
        "email_fail": "فشل إرسال البريد الإلكتروني: {error}",
        "generation_success": "✅ تم إنشاء السيرة الذاتية بنجاح!",
        "preview_tab": "📄 معاينة السيرة الذاتية",
        "cover_letter_tab": "📝 خطاب التغطية",
        "suggestions_tab": "💡 الاقتراحات",
        "interview_prep_tab": "❓ التحضير للمقابلة",
        "download_tab": "📥 تحميل",
        "cover_letter_header": "🖋️ خطاب التغطية المخصص لك",
        "download_header": "📥 قم بتنزيل سيرتك الذاتية الاحترافية",
        "download_info_admin": "وصول المسؤول: لديك عدد غير محدود من التنزيلات.",
        "download_info_user": "سيرتك الذاتية المنسقة جاهزة للتنزيل كملف PDF أدناه.",
        "download_purchase_warning": "تم استخدام النسخة التجريبية. الشراء مطلوب لتنزيل آخر.",
        "download_warning": "تم استخدام النسخة التجريبية. الشراء مطلوب لتنزيل آخر.",
        "purchase_button": "💳 شراء مقابل {price} ريال سعودي",
        "payment_info": "سيتم دمج الدفع قريبًا...",
        "download_button_label": "📄 تنزيل PDF",
        "download_caption": "سيستخدم هذا رصيدك من التجربة المجانية.",
        "pdf_fail": "عذرًا، لم نتمكن من إنشاء ملف PDF. يرجى المحاولة مرة أخرى.",
        "docx_button_label": "📝 تنزيل DOCX (قريبًا)",
        "feedback_header": "هل كان هذا مفيدًا؟",
        "feedback_yes": "👍 نعم",
        "feedback_no": "👎 لا",
        "feedback_rate": "⭐ تقييم",
        "feedback_thanks": "شكرًا لك على ملاحظاتك!",
        "feedback_improve": "سنعمل على تحسين خدماتنا. شكرًا لك!",
        "rating_slider": "قيم تجربتك",
        "submit_rating": "إرسال التقييم",
        "rating_thanks": "شكرًا لك على تقييمك بـ {rating} نجوم!",
    }
}

def get_local_text(language: str, key: str) -> str:
    """
    Returns the localized text for a given key and language.
    Defaults to English if the key is not found in the target language.
    """
    return LOCALIZATION.get(language, LOCALIZATION["en"]).get(key, LOCALIZATION["en"].get(key, key)) 